# Generated by Django 6.0.3 on 2026-03-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='MembraneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('membranes_per_box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MembraneBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('STORED', 'Stored'), ('IN_USE', 'In Use'), ('CONSUMED', 'Consumed')], default='STORED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.location')),
                ('membrane_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.membranetype')),
            ],
        ),
        migrations.CreateModel(
            name='StorageActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.membranebox')),
            ],
        ),
    ]
